var _tmr=_tmr||[];
(function(){function Db(){return ra&&Eb&&$a?(ab=[Eb-ra,$a-ra,La?La-ra:null,Ma?Ma-ra:null].join("/"),La&&Ma&&(Db=function(){return ab}),ab):null}function n(a,b,c){a.addEventListener?a.addEventListener(b,c,!1):a.attachEvent&&a.attachEvent("on"+b,c)}function L(a,b,c){a.removeEventListener?a.removeEventListener(b,c,!1):a.detachEvent&&a.detachEvent("on"+b,c)}function Fb(a,b){try{if(a.nodeName.toLowerCase()===b.toLowerCase())return a;if(a.parentNode)return Fb(a.parentNode,b)}catch(c){q&&console.warn("[TopMailRu] Error#1.25",
c)}return null}function Gb(a,b){if(null===a.offsetParent||(0==a.offsetHeight||0==a.offsetWidth||0==a.clientHeight||0==a.clientWidth)||b&&(0==a.offsetLeft||0==a.offsetTop))return!1;if(void 0!==f.getComputedStyle){var c=f.getComputedStyle(a,null);return"none"!==c.display&&"hidden"!==c.visibility}return!0}function M(a,b){for(var c=0,d=b.length;c<d;c++)if(b[c]==a)return!0;return!1}function O(a){var b=typeof a;return!("number"===b||"boolean"===b||"string"===b||a.nodeType||a===a.window)}function $(a){return"[object Array]"===
Object.prototype.toString.call(a)}function aa(){var a=arguments,b=a[0]||{},c=!1,d=1,g=a.length,h,e,k,r,u;"boolean"===typeof b&&(c=b,b=a[d++]||{});for(O(b)||(b={});d<g;d++)if(null!=(h=a[d]))for(e in h)k=b[e],r=h[e],b!==r&&(c&&r&&(O(r)||(u=$(r)))?(u?(u=!1,k=k&&$(k)?k:[]):k=k&&O(k)?k:{},b[e]=aa(c,k,r)):void 0!==r&&(b[e]=r));return b}function Hb(a,b,c){if(!a)return null;var d=a.match(b),g=2<arguments.length?c:0;return d&&d.length>g?d[g]:null}function Ib(a){return(""+a).replace(/[\/\^\$\*\+\?\.\|\(\)\[\]\{\}\\]/g,
"\\$&")}function bb(a){return Hb(a.host,/^(?:w{3}.)?(.*)$/,1)||""}function pc(a,b,c){a=bb(a);b=(b&&0<b?b:URL_HELPER__MASK_LEVEL)-1;var d=1;a=a.replace(RegExp("^.*(?:\\.((?:[^\\.]+\\.){"+b+"}[^\\.]+$))"),"$1");if(d=a.match(/\./g))d=d.length;a="(?:^|\\.{"+(b-d+1)+"})"+Ib(a)+"$";return RegExp(c?"^((?!"+a+").)*$":a)}function cb(a){var b;if($(a)){b=[];for(var c=0,d=a.length;c<d;c++)b.push(cb(a[c]));return b}b=a instanceof RegExp?a:RegExp("^"+Ib(a)+"$");return b.test(bb(C))?null:b}function Jb(a){var b=
"";try{var c=new Uint8Array(a);f.crypto.getRandomValues(c);for(var d=0;d<a;d++)b+=(c[d]%16).toString(16)}catch(g){b="";for(d=0;d<a;d++)c=Math.floor(16*Math.random()),b+=c.toString(16)}return b}function w(){return(new Date).getTime()}function D(a,b){var c={data:b,raw:a,url:db(a)},d;if(!qc||"function"!==typeof navigator.sendBeacon)d=!1;else{c.dataSplitter=";";var g=eb(c.data,c.dataSplitter);try{d=!0===navigator.sendBeacon(c.url,g)}catch(h){d=!1}}d||(void 0===b?(c.dataSplitter=";",c.open=rc,c.connect=
sc,c.startListen=tc,c.stopListen=uc,c.open(c),c.connect(c)):("function"===typeof f.XMLHttpRequest?(c.dataSplitter=";",c.open=vc,c.connect=wc,c.startListen=xc,c.stopListen=yc,c.open(c),c.connect(c),d=!0):d=!1,d||zc(c)))}function zc(a){var b=l.createElement("iframe"),c=l.createElement("div");c.setAttribute("style","position: absolute !important; top: -9999px !important; left: -9999px !important; width: 1px !important; height: 1px !important;");c.appendChild(b);l.body.appendChild(c);try{var d=b.contentWindow.document,
g=d.createElement("div"),h;for(h in a.data)if(a.data.hasOwnProperty(h)){var e=a.data[h],k=typeof e;if("string"===k||"number"===k){var r=d.createElement("input");r.setAttribute("type","hidden");r.setAttribute("name",h);r.value=e;g.appendChild(r)}}var u=d.createElement("form");u.setAttribute("action",a.url);u.setAttribute("method",Kb);u.setAttribute("enctype",Lb);u.appendChild(g);var f=d.createElement("div");f.appendChild(u);d.body.appendChild(f);var m=function(){try{L(b,"load",m),l.body.removeChild(c)}catch(a){q&&
console.warn("[TopMailRu] Error#1.2",a)}};n(b,"load",m);u.submit()}catch(s){q&&console.warn("[TopMailRu] Error#1.3",s)}}function vc(a){a._connection=new f.XMLHttpRequest}function wc(a){a._connection.open(Kb,a.url);a._connection.setRequestHeader("Content-Type",Lb);a._connection.send(eb(a.data,a.dataSplitter))}function xc(a){n(a._connection,"load",a._onload);n(a._connection,"error",a._onerror)}function yc(a){L(a._connection,"load",a._onload);L(a._connection,"error",a._onerror)}function rc(a){a._connection=
new Image}function sc(a){a._connection.src=a.url+eb(a.data,a.dataSplitter)}function tc(a){a._connection.onload=a._onload;a._connection.onerror=a._onerror}function uc(a){a._connection.onload=null;a._connection.onerror=null}function eb(a,b){var c=b||";",d="",g;for(g in a)if(a.hasOwnProperty(g)){var h=a[g],e=typeof h;if("string"===e||"number"===e)d+=c+escape(g)+"="+escape(h)}return d}function db(a){return"https://top-fwz1.mail.ru"+a}function P(a){return(a=l.cookie.match(RegExp("(?:^|; )"+a.replace(/([\.$?*|{}\(\)\[\]\\\/\+^])/g,
"\\$1")+"=([^;]*)")))?decodeURIComponent(a[1]):null}function ha(a,b,c){c=c||{};var d=c.expires;"number"===typeof c.expires&&(d=new Date,d.setTime(d.getTime()+c.expires));d&&d.toUTCString&&(d=d.toUTCString());c.expires=d;a=a+"="+encodeURIComponent(b);for(var g in c)if((b=c[g])||0===b)a+="; "+g,!0!==b&&(a+="="+b);l.cookie=a}function fb(a,b){var c=b||{};c.expires=-1;ha(a,"",c)}function Ac(){var a="tmr"+(""+Math.random()).slice(2);try{return U=f.localStorage||null,U.setItem(a,a),U.removeItem(a),!0}catch(b){return U=
null,q&&console.warn("[TopMailRu] Error#1.4",b),!1}}function ya(a){try{return U.getItem(a)}catch(b){q&&console.warn("[TopMailRu] Error#1.5",b)}return null}function za(a,b){try{U.setItem(a,b)}catch(c){q&&console.warn("[TopMailRu] Error#1.6",c)}}function Bc(){if(!V)return null;for(var a=C.hostname.split(".").reverse(),b,c=1,d=a.length;c<d;c++){b=a[0];for(var g=1;g<=c;g++)b=a[g]+"."+b;var g=""+w(),h={domain:b,path:"/",expires:3E5};try{ha("tmr_tcdhn",g,h);var e=P("tmr_tcdhn");fb("tmr_tcdhn",h);if(e===
g)return b}catch(k){q&&console.warn("[TopMailRu] Error#1.8",k)}}return null}function Mb(a,b){V&&ha(a,b,gb);ia&&za(a,b)}function hb(a,b,c){var d=l.createElement("script");d.type="text/javascript";d.async=!0;b&&(d.onload=b);c&&(d.onerror=c);d.src=a;document.body.appendChild(d)}function Nb(a){var b=";e="+escape("detect");D(J(a,"/tracker",!1,!1)+b)}function Ob(a,b){if(a.length&&null!==b.ecom_data){var c=wa(b.ecom_data),c=c?(""+c).substring(1,c.length-1):"";if(!(4096<c.length||-1===c.search(/\S/))){var d=
ib("_m",b.ecom_method),g=ib("_t",b.ecom_type),h=ib("_jst",Pb()),c="{"+c+d+g+h+"}";D(J({id:a[0]},"/datalayer",!1,!0)+(";ids="+escape(a.join()))+(";e="+escape(c)))}}}function ib(a,b){var c=',"'+a+'":';if(!b||!b.length)return c+"[]";try{return c+'["'+b.join('","')+'"]'}catch(d){}return c+"false"}function Cc(){var a=P(Qb);if(null===a)return null;a=a.split("|");if(3!==a.length)return null;var b=a[2],b=w()-b;return 0>b||b>Rb?null:{id:a[0],version:a[1]}}function Sb(a){jb=!0;a.length&&hb(db("/js/dyn-goal-config.js?ids="+
a.join(",")))}function m(){}function ja(a){a&&"object"===typeof a&&(!ba&&"id"in a)&&(ba=a.id)}function sa(a){return!Na?void 0:Na[a]}function Dc(a){return(a=sa(a))&&Oa?a-Oa:void 0}function Tb(){if(Na){for(var a=0,b="domInteractive domContentLoadedEventStart domContentLoadedEventEnd domComplete loadEventStart loadEventEnd".split(" "),c=0;c<b.length;c++){var d=sa(b[c]);if(0<d&&(d<a||0==a))a=d}return a?a:void 0}}function W(a,b){var c=1<arguments.length?b:ba;return a&&"object"===typeof a&&("id"in a&&a.id||
c)}function Ub(a,b,c,d){var g=parseInt(a,10);return isNaN(g)||""+g!==""+a||g<b||g>c?d||0===d?d:null:g}function Vb(a,b){if("URL"in window){var c=b;try{c=new URL(a)}catch(d){return b}return c?a:b}return a||b}function J(a,b,c,d){ia&&za(ta,++Q);var g="id"in a?a.id:ba,h=Vb(a.url,C.href),e=Vb(a.referrer,l.referrer),k="title"in a?a.title:l.title,r;r=kb;null===r&&(r=Ec());r=null!==r?r?1:0:null;var u="userid"in a?a.userid:R||0===R?R:void 0,m=ca?ca:void 0,n;n=ka&&a.bfCache;var s="pageView"===a.type&&a.timespent,
p=[];ba&&g!==ba&&p.push("sec");"dataLayer"in f&&p.push("dl");E&&p.push(["ecom"].concat(E).join("-"));var Aa=Fc();Aa&&Aa.length&&p.push(["jst"].concat(Aa).join("-"));n&&p.push("bfc");S&&s&&p.push("ts");f.top!==f&&p.push("frame");n=p.join(",");s=(new Date).getTimezoneOffset();p="";if(f.Intl)try{p=f.Intl.DateTimeFormat().resolvedOptions().timeZone||""}catch(Gc){q&&console.warn("[TopMailRu] Error#1.1",Gc)}Aa=s+"/"+p;s=Wb;s=null!==s?s:Cc();p=Db();a.start=Tb();b=b+"?_="+Math.random()+(g?";id="+escape(g):
"")+(h?";u="+escape(h):"")+(e?";r="+escape(e):"")+(a.start?";st="+escape(a.start):"");g=Ub(a.gender,1,2);b+=null!==g?";gender="+g:"";g=Ub(a.age,1,127);d=b+(null!==g?";age="+g:"")+("pid"in a?";pid="+escape(a.pid):"")+(void 0!==u?";userid="+escape(u):"")+(void 0!==m?";uparams="+escape(wa(m)):"")+(d&&k?";title="+encodeURIComponent(k):"");k=";s="+Hc+";vp=";m=u=0;l.documentElement&&(l.documentElement.clientWidth||l.documentElement.clientHeight)?(u=l.documentElement.clientWidth,m=l.documentElement.clientHeight):
"number"==typeof f.innerWidth&&(u=f.innerWidth,m=f.innerHeight);d=d+(k+(""+u+"*"+m)+";touch="+Ic+";hds="+Jc)+";sid="+lb+";ver="+Kc+";tz="+encodeURIComponent(Aa);if(c){if(!Na||!mb)c="";else{c=[];c.push(mb.type);c.push(mb.redirectCount);c.push(Oa);for(k=0;k<Xb.length;k++)c.push(Dc(Xb[k]));c=c.join("/")}c=";nt="+c}else c="";c=d+c+(p?";ct="+p:"")+(Pa?";gl="+Pa:"")+("device"in a?";device="+escape(a.device):"")+";ni=";if(!F||!F.connection)p="";else{p=F.connection;d=[];for(u=0;u<Yb.length;u++){k=p[Yb[u]];
if(void 0!==k)switch(k){case !0:k=1;break;case !1:k=0;break;default:k=(""+k).replace(/\//g,"_")}d.push(k)}p=d.join("/")}return c+p+("params"in a?";params="+escape(wa(a.params)):"")+(null!==r?";detect="+r:"")+(V||ia?";lvid="+escape([ua,w(),Q,la].join(":")):"")+(n?";opts="+escape(n):"")+(s?";flocid="+escape(s.id)+";flocv="+escape(s.version):"")+(Zb&&Ba?";fpid="+Ba:"")+("version"in a?";appver="+escape(a.version):"")+(ma.support?";visible="+ma.getValue():"")+";js=13"}function nb(a){a=";e="+escape(a);
for(var b=0;b<G.length;b++)D(J(G[b],"/tracker",!1,!0)+a)}function Lc(){kb=!0;$b(1);if(!ob&&!Ca){Ca=!0;for(var a=0;a<G.length;a++)Nb(G[a])}}function Mc(){$b(0);kb=!1}function Ec(){var a=P(ac);if(null===a)return null;a=a.split("|");if(2!==a.length)return null;var b=a[1],b=w()-b;if(0>b||b>bc)return null;a=parseInt(a[0],10);return isNaN(a)?null:a}function $b(a){var b=w();a=[a,b].join("|");ha(ac,a,{path:"/",expires:bc})}function Nc(){var a=0;Qa&&(a=w()-Qa);Oc||(x.dcl3=setTimeout(function(){nb("DCL/3")},
Math.max(3E3-a,0)))}function Pc(){var a=0;Ra&&(a=w()-Ra);Qc||(x.pvt2=setTimeout(function(){nb("PVT/2")},Math.max(2E3-a,0)));Rc||(x.pvt15=setTimeout(function(){nb("PVT/15")},Math.max(15E3-a,0)))}function cc(){pb||setInterval(function(){_tmr.beat()},6E4)}function Sc(a,b,c,d){if(!b||!d||d===qb&&b===qb&&c===qb)return null;b={goal:Tc+b,value:c||0,params:{product_id:d}};a&&(b.id=a);return b}function Sa(){Qa=w();l.addEventListener?(L(l,"DOMContentLoaded",Sa),_tmr.onready()):l.attachEvent&&"complete"===l.readyState&&
(L(l,"readystatechange",Sa),_tmr.onready());dc()}function rb(a){Ra=w();if(ka){if(a.persisted){Da=Ea=Ta=0;sb=tb=!1;S&&y.launch();a=ub;ub=[];for(var b=0,c=a.length;b<c;b++)_tmr.callbackOnReady(a[b]);a=Ua;Ua={};for(b in a)_tmr.pageView(a[b]);cc()}}else L(f,"load",rb);_tmr.onready();_tmr.onload()}function Fa(){ka||(L(f,"unload",Fa),L(f,"beforeunload",Fa));_tmr.unload()}function dc(){S&&y.launch();if(Uc&&ec){window.addEventListener("message",function(a){var c=null;try{if(c=a.data,O(c)||(c=Va(c)),"LOAD_BUTTONS_SCRIPT"===
c.type){var d;var g=document.referrer;a=null;var h=(""+c.lang).toLowerCase(),e;b:{for(var c=0,k=vb.length;c<k;c++)if(vb[c]===h){e=!0;break b}e=!1}e||(h=vb[0]);try{a=(new URL(g)).host}catch(r){}d=a&&Vc.test(a)?"https://"+a+"/top_constructor/buttons_"+h+".js":db("/js/dyn-goal-wizard-"+h+".js");hb(d)}}catch(f){}});if(window.opener)try{window.opener.postMessage({type:"READY"},document.referrer)}catch(a){}jb||(Wa.push.apply(Wa,Ga),Sb(Ga))}}if("[object Array]"===Object.prototype.toString.call(_tmr)){var Eb=
(new Date).getTime(),$a=null,La=null,Ma=null,ra=null,ab=null,f=window,F=navigator,l=document,C=location,X="string"===typeof C.hostname?C.hostname:"",Ha=-1!=X.search(/(^|\.)odnoklassniki\.ru$/)||-1!=X.search(/(^|\.)ok\.ru$/),fc=-1!=X.search(/(^|\.)vk\.com$/);X.search(/(^|\.)mail\.ru$/);var Wc=-1!=X.search(/(^|\.)lamoda\.ru$/),Xc=-1!=X.search(/(^|\.)kommersant\.ru$/);X.search(/(^|\.)top\.mail\.ru$/);X.search(/(^|\.)dzen\.ru$/);var gc="string"===typeof C.search&&-1!=C.search.search(/[?&]rb_clickid=/),
q="string"===typeof C.search&&-1!=C.search.search(/[?&]tmr_debug=1(?:&|$)/),qc=!1,pb=Ha||fc||Wc||Xc,Qc=!gc,Rc=Ha,Oc=!gc,ob=!1,S=f.performance&&"visibilityState"in l,Yc=[36383],Zc=!(Ha||fc),Uc=!0,Zb=!0,hc=f.JSON&&f.JSON.stringify&&f.JSON.parse,ka="onpageshow"in f&&"onpagehide"in f,ec="URL"in f,wa=hc?f.JSON.stringify.bind(f.JSON):function(a){return""},Va=hc?f.JSON.parse.bind(f.JSON):function(a){return{}},vb=["ru","en"],Vc=/^(ads\d+\.my\.com)$/,Kb="POST",Lb="application/x-www-form-urlencoded",V=!(0===
C.hostname.search(/^(\d+.)+\d+$/g)||-1!==C.hostname.search(/:/g)),U=null,ia=Ac(),gb={domain:Bc(),path:"/",expires:287712E5};(function(){var a;if(a=l.cookie.match(RegExp("(?:^|; )(tmr_tcdhn\\d+)=([^;]*)","g"))){for(var b=[],c,d=0,g=a.length;d<g;d++)c=a[d],(c=c.match(/(?:^|; )(tmr_tcdhn\d+)=([^;]*)/))&&b.push(c.slice(1));a=b}else a=null;if(a){d=0;for(g=a.length;d<g;d++)b=a[d][0],fb(b,gb)}})();var Ca=!1,kb=null,bc=864E5,ac="tmr_detect",$c=function(){function a(a,b){for(var c=a.length,e,k,f=0;f<b;f++)k=
Math.floor(Math.random()*c),e=a[f],a[f]=a[k],a[k]=e;return a.slice(0,b)}function b(b,g){var h=l.createElement("div"),e=String.fromCharCode(97,100,118,98,108,111,99,107,32,97,100,118,101,114,116,98,108,111,99,107,32,97,100,118,101,114,116,66,108,111,99,107,32,98,45,114,98,32,98,97,110,110,101,114,95,50,52,48,32,112,45,116,97,114,103,101,116,32,112,117,98,95,51,48,48,120,50,53,48,32,112,117,98,95,51,48,48,120,50,53,48,109,32,112,117,98,95,55,50,56,120,57,48,32,114,98,95,98,111,100,121,32,114,98,45,
102,108,111,97,116,105,110,103,32,114,98,45,115,108,111,116,32,114,98,45,118,105,100,101,111,45,119,105,100,103,101,116,32,116,101,120,116,45,97,100,32,116,101,120,116,45,97,100,45,108,105,110,107,115,32,116,101,120,116,45,97,100,115,32,116,101,120,116,45,98,97,110,110,101,114,32,116,101,120,116,95,97,100,32,116,101,120,116,95,97,100,115,32,116,101,120,116,65,100,32,116,101,120,116,97,100,32,116,101,120,116,65,100,115,32,116,101,120,116,97,100,115,32,116,103,98,45,98,97,110,110,101,114,32,116,114,
103,45,98,45,98,97,110,110,101,114,45,98,108,111,99,107).split(" "),e=a(e,c);h.setAttribute("class",e.join(" "));h.setAttribute("style","position: absolute !important; top: -9999px !important; left: -9999px !important; width: 1px !important; height: 1px !important;");h.setAttribute("id","trg-b-banners-1");h.setAttribute("data-view","SlotView.mimic");this.bait=l.body.appendChild(h);this.bait.offsetParent;this.bait.offsetHeight;this.bait.offsetLeft;this.bait.offsetTop;this.bait.offsetWidth;this.bait.clientHeight;
this.bait.clientWidth;this.loopNumber=0;this.fnPositive=b||null;this.fnNegative=g||null;var k=this;setTimeout(function(){k._checkBait.call(k)},1)}var c=7;b.prototype._checkBait=function(){if(Ca)this._stop();else{var a=null!==l.body.getAttribute("abp")||!Gb(this.bait,!0);(!0===a||10<=++this.loopNumber)&&this._stop();var b;if(a&&this.fnPositive)try{b=this.fnPositive,b()}catch(c){q&&console.warn("[TopMailRu] Error#1.9",c)}else if(!a&&10>this.loopNumber){var e=this;setTimeout(function(){e._checkBait.call(e)},
50*this.loopNumber)}else try{b=this.fnNegative,b()}catch(k){q&&console.warn("[TopMailRu] Error#1.10",k)}}};b.prototype._stop=function(){try{l.body.removeChild(this.bait)}catch(a){q&&console.warn("[TopMailRu] Error#1.11",a)}};return function(a,c){new b(a,c)}}(),E=null,ic="ecommerce",B="dataLayer",da=null,wb=!1,Xa=[],ad=[36383,2540645,3171181,3074137,2057653],bd=[],xb;(function(){function a(a,b){for(var c=0,d=b.length;c<d;c++)-1===a.indexOf(b[c])&&a.push(b[c])}function b(b,c,d){for(var g={ecom_method:[],
ecom_type:[],ecom_data:{events:[]}},h=0,k=b.length;h<k;h++){var e=n[b[h]];if(e){a(g.ecom_method,[b[h]]);for(var f=0,u=e.length;f<u;f++)for(var r=0,l=d.length;r<l;r++){var p=e[f][d[r]];if(p)for(var t=0,m=c.length;t<m;t++)if(-1!==e[f].type.indexOf(c[t])){a(g.ecom_type,[c[t]]);a(g.ecom_data.events,p);break}}}}return g}function c(a,b,c){if(!a||!c||!(b in n))return null;for(var d,g=0,h=n[b].length;g<h;g++)if(d=n[b][g],c in d&&-1!==d[c].indexOf(a))return{ecom_method:[b],ecom_type:d.type.slice(),ecom_data:{}};
return null}function d(a){for(var d=[],e,f,l=0,cd=a.length;l<cd;l++)if(f=a[l]){e=null;try{if(f.ecommerce)e=g(f)||h(f);else if(null===f.ecommerce)e=null;else if(f.event){var m={event:f.event,ecommerce:{}};e=g(m)||h(m)}else if("event"===f[0]){var na=f[1],n=f[2],z=c(na,r,s);z&&(z.ecom_data[na]=n);e=z}else if(f.event===ic)a:{for(var Ia=b([k],[u],[p]),yb=0,t=Ia.ecom_data.events.length;yb<t;yb++)if(!f.hasOwnProperty(Ia.ecom_data.events[yb])){e=null;break a}delete Ia.ecom_data.events;Ia.ecom_data[ic]=f;
e=Ia}}catch(w){q&&console.warn("[TopMailRu] Error#1.23",w),e=null}e&&(d.push(e),Xa.push(e))}if(d.length){a=0;for(e=d.length;a<e;a++)Ob(Ya,d[a]);E||(E=[0,0,B]);E[0]+=d.length;e=a=0;for(l=d.length;e<l;e++)a+=wa(d[e].ecom_data).length;E[1]+=a}}function g(a){var b,d;for(d in a.ecommerce)if(a.ecommerce.hasOwnProperty(d)&&(b=c(d,k,l))){if(a.event&&(d=c(a.event,k,m)))for(var g=0,e=b.ecom_type.length;g<e;g++)-1===d.ecom_type.indexOf(b.ecom_type[g])&&(b.ecom_type.splice(g,1),e--,g--);b.ecom_data=a.ecommerce;
return b}return null}function h(a){var b=a.event,d=c(b,k,m);d&&(d.ecom_data[b]=a.ecommerce);return d}function e(a){if((a=f[a])&&"function"===typeof a.push)d(a),da=a.push,a.push=function(){var a=da.apply(this,arguments);d([].slice.call(arguments,0));return a}}var k="push",r="gtag",u="gse",l="inner",m="outer",s="external",p="required",n={};n[r]=[{type:["gee"],external:"add checkout checkout_option checkout_progress click detail promo_click remove select_content set_checkout_option view_refund".split(" ")},
{type:["ga4"],external:"earn_virtual_currency join_group level_end level_start level_up post_score select_content spend_virtual_currency tutorial_begin tutorial_complete unlock_achievement ad_impression login search share sign_up add_payment_info add_shipping_info add_to_wishlist generate_lead select_item select_promotion view_cart view_item_list".split(" ")},{type:["gee","ga4"],external:"add_to_cart begin_checkout purchase refund remove_from_cart view_item view_promotion".split(" ")}];n[k]=[{type:[u],
required:["transactionId","transactionTotal"]},{type:["ga4"],outer:b([r],["ga4"],[s]).ecom_data.events},{type:["gee"],inner:"click checkout checkout_option impressions promoClick promoView refund".split(" "),outer:"addToCart checkout checkoutOption productClick productDetail ProductImpressions promotionClick promotionView removeFromCart transactionPush".split(" ")},{type:["ym","gee"],inner:["add","detail","purchase","remove"]},{type:["mt"],outer:["mt_order","mt_refund"]}];xb=function(a){if(!(a===
B&&da)){a!==B&&(Xa=[]);var b=f[B];b&&"function"===typeof b.push&&da&&(b.push=da,da=null);e(a);wb=!0}}})();var Pb=function(){var a=[{id:"gtag",globalVars:["google_tag_manager"]},{id:"ga",globalVars:["GoogleAnalyticsObject"]},{id:"ym",globalVars:["Ya",{re:"yaCounter\\d+"}]},{id:"vk",globalVars:["VK"]},{id:"vk",globalVars:["vkAsyncInit"]}],b={};return function(){var c;try{c=Object.keys(f).join(",")}catch(d){c=null}for(var g=[],h,e=0,k=a.length;e<k;e++){h=b[a[e].id];if(void 0===h)a:{h=a[e].globalVars;
for(var r=c,u=0,l=h.length;u<l;u++){var m=h[u];if("string"===typeof m&&!(m in f)||"string"===typeof m.re&&(r&&-1===r.search(RegExp("($|,)"+m.re+"(,|^)","m"))||1===l)){h=!1;break a}}h=!0}h&&(b[a[e].id]=!0,M(a[e].id,g)||g.push(a[e].id))}return g}}(),Fc=Pb,Rb=864E5,Qb="tmr_floc",Wb=null;(function(a){try{l.interestCohort&&"function"===typeof l.interestCohort&&l.interestCohort().then(function(a){Wb={id:a.id,version:a.version};a=[a.id,a.version];var b=w();a=a.concat(b).join("|");ha(Qb,a,{path:"/",expires:Rb})},
function(){})}catch(b){}})();var zb=!1,Pa=null,Ja=null,Ab=!1,jc;(function(){function a(a){try{var c=a.state;Ja=c in e?e[c]:h;Ab=c===g;zb&&b(Ab)}catch(d){}}function b(a){try{a?(F[d].getCurrentPosition(c),f||(f=F[d].watchPosition(c))):(f&&F[d].clearWatch(f),c(null))}catch(b){}}function c(a){if(a)try{var b=a.coords,b=[b.latitude,b.longitude,b.accuracy,b.altitude,b.altitudeAccuracy,b.heading,b.speed];a=0;for(var c=b.length;a<c;a++)"number"!==typeof b[a]&&(b[a]="");b.splice(0,0,Ja);Pa=b.join("/")}catch(d){}else Pa=
Ja}var d="geolocation",g="granted",h="u",e={denied:"d"};e[g]="g";e.prompt="p";var f=null;(function(){Ja=h;c(null);try{d in F?F.permissions&&F.permissions.query({name:d}).then(function(b){a(b);b.onchange=function(){a(b)}}):Ja="n"}catch(b){}})();jc=b})();var ma={support:!1},ma=function(){function a(){g(e)}function b(){g(e,s)}function c(a){a.persisted&&(p[e]=null,p[k]=null,g(e,q))}function d(){return r?!l[r]:null}function g(a,b){var c=w(),g="undefined"===typeof b?d():b;if(null===p[a])p[a]={ts:c,state:g,
total:0};else{var e=p[a];if(e.state!==g&&!(e.state===s&&g!==q)){var f=c-e.ts,k=e.state;e.ts=c;e.state=g;f<h||(k===q?(e.total+=f,y&&y(c,f)):k===x&&v&&v(c,f))}}}var h=5,e="auto",k="user",r=null,m=null,q=!0,x=!1,s=null;"hidden"in l?(r="hidden",m="visibilitychange"):"mozHidden"in l?(r="mozHidden",m="mozvisibilitychange"):"webkitHidden"in l?(r="webkitHidden",m="webkitvisibilitychange"):"msHidden"in l&&(r="msHidden",m="msvisibilitychange");var p={};p[e]=null;var y=p[k]=null,v=null;return{support:!!r,auto:function(d,
g){y=d||null;v=g||null;r&&(a(),n(l,m,a));ka?(n(f,"pageshow",c),n(f,"pagehide",b)):(n(f,"beforeunload",b),n(f,"unload",b))},set:function(a){g(k,!!a)},getLog:function(){var a=w(),b={},c,d;for(d in p)c=p[d],b[d]=c?c.total:0,c&&c.state&&(b[d]+=a-c.ts);return b},getValue:d}}();ma.auto();var kc={enabled:!1};if(ec){var lc=function(){var a="checkbox color date datetime-local email file month number password radio range search tel text time url week".split(" ");return{analyze:function(b){if(!b)return null;
for(var c=[].slice.apply(b.elements),d=[],g=[],f=0,e=c.length;f<e;f++){var k;a:switch(k=c[f],k.tagName.toLowerCase()){case "button":k=!1;break a;case "input":var l=k.type.toLowerCase();if(l&&-1===a.indexOf(l)){k=!1;break a}default:k=Gb(k,!1)&&k.name&&!1===k.disabled}k&&(d.push(c[f].name),g.push(c[f].type))}return{node:b,inputsName:d.length?d:null,inputsType:g.length?g:null}},getFormByInput:function(a){if(!a)return null;a=a.form||a.getAttribute("form");return"string"===typeof a?document.getElementById(a)||
null:a instanceof HTMLElement?a:null}}}(),kc=function(){function a(a){a=a||f.event;var c=(a.which||a.keyCode)===L;if("which"in a&&a.which===G||"button"in a&&a.button&G||c){a:{a=a.target||a.srcElement;for(var c=0,d=e.length;c<d;c++){var l;b:{l=a;for(var z=e[c],p=0,n=z.types.length;p<n;p++){var t;c:{var s=l;t=z.types[p];var A=null;if(t.filter.tagName)for(var K=0,v=t.filter.tagName.length;K<v&&!(A=Fb(s,t.filter.tagName[K]));K++);else A=s;if(A){if(t.filter.attr)for(s in s=void 0,t.filter.attr)if(t.filter.attr.hasOwnProperty(s)&&
(K=t.filter.attr[s],v=A[s],!0===K&&!v||!1===K&&v||$(K)&&-1===K.indexOf(v))){t=null;break c}t={source:A,type:t.type,detail:A.tagName}}else t=null}if(t){t.category=z.category;l=t;break b}}l=null}if(l){a=l;break a}}a=null}if(a){if(a.category===g){try{a.data=new URL(a.source.href)}catch(D){}if(!a.data)return}else if(a.category===h){if(a.data=lc.analyze(lc.getFormByInput(a.source)),!a.data)return}else return;c=J;if(c.enabled&&c.modes){d=0;for(l=c.modes.length;d<l;d++)if(z=a,p=c.modes[d],z.category===p.mode)if(z.category===
g||z.category===h){if(p=p.categories,z.data){n=void 0;c:{n=0;for(t=p.length;n<t;n++){for(var A=z,s=p[n],K={category:z.category},v=[],T=0,C=s.types.length;T<C;T++){var pa=s.types[T],E=aa({type:s.category},K),M=y in pa,F;w in pa?F=b(A,pa,E,w):M&&(F=aa({source:A.source,data:A.data,detail:pa.type},E));if(F&&(!M||!b(A,pa,E,y)))if(v.push(F),(pa.rule&x)!==x)break}if(A=v.length?v:null){n=A;break c}}n=null}if(n){z=0;for(p=n.length;z<p;z++)c:{t=n[z];A={type:"sendEvent",category:"_"+t.category,action:t.detail};
if(t.category===g&&(t.type===k||t.type===m)){if(A.label=t.data.href,!A.label)break c}else if(t.category===u&&(A.label=t.data.node.action,!A.label))break c;_tmr.push(A)}}}}else q&&console.warn("[TopMailRu] Error#1.24","Not found tracking for type",z.type)}}}}function b(a,b,d,g){var e=!1,f=b[g];if($(f)){var h=b[g+"Rule"]||D;g=(h&s)===s;for(var h=(h&p)===p,k=0,l=f.length;k<l&&!(e=c(a,f[k]),g&&e);k++)if(h&&!e)return null}else e=c(a,f);return!e?null:aa({source:a.source,data:a.data,detail:b.type},d)}function c(a,
b){var c=b.rule||D,g=(c&s)===s,c=(c&p)===p,e=!1,f;for(f in b)if(b.hasOwnProperty(f)&&"rule"!==f){var e=b[f],h;switch(f){case "domain":h=bb(a.data);break;case "fileExtension":h=Hb(a.data.pathname,/.\.([^\.]+)$/,1)||"";break;default:h=a.data[f]}e=!0===e?!!($(h)?h.length:h):!1===e?!($(h)?h.length:h):d(h,e);if(g&&e)break;else if(c&&!e)return!1}return e}function d(a,b){var c=a;if(c)if($(c)){if(!c.length)return!1}else c=[c];else return!1;var d=b,e=D;if(O(d)&&!$(d)){if(!$(d.value))return!1;e=d.rule||e;d=
d.value}a:{for(var g=(e&v)===v,f=(e&s)===s,e=(e&p)===p,h=!1,k=0,l=d.length;k<l;k++){var m=d[k];if(m){var n="string"===typeof m;n&&!g&&(m=m.toLowerCase());var r=m instanceof RegExp;if(n||r){var h=!0,q;b:{q=c;for(var u=g,w=0,y=q.length;w<y;w++){var x=u?q[w]:q[w].toLowerCase();if(r&&m.test(x)||n&&m===x){q=!0;break b}}q=!1}if(f&&q){c=!0;break a}else if(e&&!q){c=!1;break a}}}}c=f?!1:e?h?!0:!1:void 0}return c}var g="click",h="submit",e=[{category:h,types:[{type:"button",filter:{tagName:["input","button"],
attr:{type:["submit","image"]}}}]},{category:g,types:[{type:"a",filter:{tagName:["a"],attr:{href:!0}}}]}],k="file",m="resource",u="submit",w="filter",y="stop",s=1,p=2,v=4,x=8,D=s,J={enabled:!0,modes:[{mode:h,categories:[{category:u,types:[{type:"lead",filter:[{inputsName:["phone"],inputsType:["tel"],rule:s},{inputsName:["email"],inputsType:["email"],rule:s}],filterRule:p,stop:{inputsName:{value:["password"]}}},{type:"form",filter:{inputsName:!0}}]}]},{mode:g,categories:[{category:"contact",types:[{type:"email",
filter:{protocol:["mailto:"]}},{type:"phone",filter:{protocol:["tel:"]}}]},{category:k,types:[{type:"file",filter:{fileExtension:"7z bz2 gz apk iso cab dmg msi rar tar zip exe txt doc docx ppt pptx xls xlsx csv pdf psd rtf ods djvu eps 3gp aac ac3 avi flac flv divx midi mka mkv mp3 mp4 mpeg mpg mov ogg vob wav webm wma wmf wmv torrent".split(" ")}}]},{category:m,types:[{type:"outgoing",rule:x,stop:{domain:[pc(C.host,3,!1)],href:[/password/]}},{type:"messenger",filter:{domain:cb("vk.me t.me telegram.me telegram.im web.telegram.org m.me web.whatsapp.com api.whatsapp.com chat.whatsapp.com wa.me".split(" "))},
stop:{href:[/password/]}},{type:"social",filter:{domain:cb("vk.com vkontakte.ru m.vk.com vk.ru ok.ru m.ok.ru odnoklassniki.ru facebook.com m.facebook.com fb.com twitter.com linkedin.com instagram.com tiktok.com youtube.com youtu.be m.youtube.com".split(" "))},stop:{href:[/password/]}}]}]}]},G=1,L=13;return{enabled:!0,start:function(){n(l,"click",a);n(l,"keypress",a)}}}();Zc&&kc.start()}var y=function(){function a(){b(null)}function b(a){g();a?(V=a===T,oa=a):oa=Z&&null!==V?V?T:ca:l.visibilityState;
a=B();for(var b in ea)y(b,a)}function c(){if(!1!==P){L(f,A,ja);ja=null;f.clearInterval(la);ma=la=null;L(l,K,da);da=null;Z&&(L(f,X,ga),L(f,aa,ha),ha=ga=null);h(!0);for(var a in Y){var b=a,c=Y[b];c&&(c=c.key,O(b),na(),delete Y[b],z(null,c))}H=null;fa=[];va=[];I={};Y={};ea={};P=!1}}function d(a,b,c){var d=a+"_"+b;if(d in I)return!1;var e=w(),g=B(),f=C(d,e,lb);b=I[d]={id:a||null,name:b,key:f,canUseInBackground:!!c,startTS:e,updateTS:g,timespent:{}};if(a)if(va.push(d),d=b.canUseInBackground,b=ea[a]){if(c=
b.isActive,!c&&(e=H&&M(a,H)))if(c=oa===T||d)b.updateTS=g,b.isActive=!0}else e=H&&M(a,H),c=oa===T||d,ea[a]={isActive:e&&c,updateTS:g,timespent:{}};else fa.push(d);return!0}function g(a,b){var c,d;2>arguments.length?(c=va.concat(fa),d=R):(c=[a+"_"+b],d=W);e(c,d)}function h(a,b,c){var d=!1,g=[],f=[];2>arguments.length?(g=va.slice(),(d=!!arguments[0])&&(g=g.concat(fa))):(d=a+"_"+b,-1!==va.indexOf(d)?g=[d]:-1!==fa.indexOf(d)&&(c?g=[d]:f=[d]));e(g,ba);e(f,W)}function e(a,b){var c=B(),d=[],e,g,f;e=0;for(g=
a.length;e<g;e++)f=a[e],-1!==va.indexOf(f)?k(f,b,c):-1!==fa.indexOf(f)&&d.push(f);e=0;for(g=d.length;e<g;e++)f=d[e],k(f,b,c);if(b===R&&(U=c,U-P>=ra)){for(var h in I)q(h);for(h in Y)if(c=h,d=Y[c])O(c),z(c,d.key);P=U}}function k(a,b,c){var d=I[a];if(d&&!1!==d.updateTS)if(d.timespent[oa]=(d.timespent[oa]||0)+(c-(d.updateTS||U)),-1!==fa.indexOf(a)&&E(null,c),b===ba)d.updateTS=!1,q(a);else if(b===t){d.updateTS=c;var e;a:{if(b=I[a])for(e in b.timespent)if(b.timespent[e]>qa){e=!1;break a}e=!0}e?(m(a),na()):
q(a)}else d.updateTS=b===R?null:c,m(a),na()}function m(a,b,c){var d=I[a];if(!d)return null;var e=b||d.key;b=N[e];N[e]={uid:a,name:d.name,counterID:c||d.id||H,canUseInBackground:d.canUseInBackground,isActive:!1!==d.updateTS,startTime:d.startTS,timespent:{}};a=N[e].timespent;var d=d.timespent,g;for(g in d)a[g]=d[g];if(c&&(c=ea[c]))if(e=N[e]){e.common={};e=e.common;c=c.timespent;for(var f in c)e[f]=c[f]}return b||null}function q(a){var b=I[a];b&&(m(a),v(a,b.key))}function v(a,b){var c=N[b];if(c)if($(c.counterID)){var d=
N[b];if(d){var c=d.counterID,e=[],g,f,h,k;if(c){h=0;for(k=c.length;h<k;h++){f=c[h];g=C(b,f);e.push(g);f=m(a||d.uid,g,f);var l=void 0;f&&(l=N[g],Q(l.timespent,f.timespent),f.common&&(l.common=l.common||{},Q(l.common,f.common)))}}delete N[b];na();if(a&&a in I)if(d.isActive){s(a);h=0;for(k=c.length;h<k;h++)if(d=ea[c[h]])for(var n in d.timespent)d.timespent[n]=0}else p(a);h=0;for(k=e.length;h<k;h++)x(e[h])}}else if(n=N[b])(c=a&&a in I)&&!n.isActive&&p(a),e=x(b),c&&(e&&n.isActive)&&s(a)}function x(a){var b;
if(b=N[a]){var c=S(b.timespent);if(!1===b.canUseInBackground&&b.isActive&&0===c.fg)b=null;else{c=[b.name,b.startTime,b.canUseInBackground?1:0,c.fg,c.bg];if(b.common){var d=S(b.common);(d.fg||d.bg)&&c.push(d.fg,d.bg)}b={id:b.counterID,msg:c.join("/")}}}else b=!1;if(!b)return!1;c=";e="+escape("TS:"+b.msg);D(J({id:b.id},"/tracker",!1,!1)+c);delete N[a];na();return!0}function s(a){if(a=I[a])for(var b in a.timespent)a.timespent[b]=0}function p(a){if(a in I){var b;-1!==(b=fa.indexOf(a))&&fa.splice(b,1);
if(-1!==(b=va.indexOf(a)))if(va.splice(b,1),b=I[a].id){var c=ea[b];if(c){var d=c.isActive;d&&G(c,B());d=F(b,a);d||(c.isActive=!1)}}delete I[a]}}function y(a,b){var c=ea[a];if(c){var d=H&&M(a,H),e=F(a);c.isActive=d&&e;c.updateTS=b}}function E(a,b){if(a){var c=ea[a];c&&(c.isActive?G(c,B()):c.updateTS=b)}else for(c in ea)E(c,b)}function F(a,b){for(var c in I)if(c!==b&&I[c].id===a&&(oa===T||I[c].canUseInBackground))return!0;return!1}function G(a,b){a&&(a.timespent[oa]=(a.timespent[oa]||0)+(b-a.updateTS),
a.updateTS=b)}function C(a){return[].join.call(arguments,"_")}function Q(a,b){for(var c in b)a[c]=(a[c]||0)+(b[c]||0)}function S(a){var b=a[T]||0,c=0,d;for(d in a)d!==T&&(c+=a[d]);return{fg:b,bg:c}}function B(){return Math.floor(f.performance.now())}function na(){if(ia){var a={};a[ta]=N;a[ua]=xa;za(sa,wa(a)||"")}}function O(a){var b=Y[a];b&&(xa[b.key]={uid:a,name:b.name,counterID:b.id,value:b.value})}function z(a,b){if(xa[b]){var c;if(c=xa[b])if(0===c.value)c=null;else{var d=[c.name,c.value].join("/");
c={id:c.counterID,msg:d}}else c=!1;c&&(d=";e="+escape("TS:"+c.msg),D(J({id:c.id},"/tracker",!1,!1)+d));!1!==c&&(delete xa[b],na());if(c&&a&&(c=Y[a]))c.value=0}}var W=1,R=2,t=4,ba=8,A=ka?"pagehide":"unload",K="visibilitychange";"mozHidden"in l?K="mozvisibilitychange":"webkitHidden"in l?K="webkitvisibilitychange":"msHidden"in l&&(K="msvisibilitychange");var X="focus",aa="blur";"onfocusin"in l&&(X="focusin",aa="focusout");var T="visible",ca="hidden",pa=["0"],Z=!1,qa=100,ra=12E4,P=!1,U=!1,H=null,fa=[],
va=[],I={},oa,V=null,la,ma,da,ga,ha,ja,sa="tmr_tslog",ta="activity",ua="count",N={},Y={},xa={},ea={};return{init:function(){if(ia){var a=Va(ya(sa)||"{}");N=a[ta]||{};xa=a[ua]||{}}for(var b in N)v(null,b);for(b in xa)z(null,b)},launch:function(){!1===P&&(P=B(),U=B(),oa=Z&&null!==V?V?T:ca:l.visibilityState,ja=c.bind(f),n(f,A,ja),ma=a.bind(f),la=f.setInterval(ma,1E4),da=b.bind(f,null),n(l,K,da),Z&&(ga=b.bind(f,T),ha=b.bind(f,ca),n(f,X,ga),n(f,aa,ha)))},enable:function(a){if(H){if(M(a,H))return;e(fa,
t)}else{for(var b=0,c=pa.length;b<c;b++)d(null,pa[b],!1);H=[]}H.push(a);y(a,B())},disable:function(a){if(H){var b;a:{b=0;for(var c=H.length;b<c;b++)if(H[b]==a)break a;b=-1}if(-1!==b&&(e(fa,t),H.splice(b,1),b=B(),a=ea[a]))a.isActive=!1,a.updateTS=b}},startActivity:d,updateActivity:g,stopActivity:h,incCount:function(a,b){var c=a+"_"+b,d;if(!(d=Y[c]))if(c in Y)d=Y[c];else{d=w();var e=C(b,d,lb);d=Y[c]={id:a,name:b,key:e,startTS:d,value:0}}d&&d.id===a&&(d.value++,O(c),na())},defaultID:function(){return H?
H[0]:void 0}}}(),jb=!1,Ba=null;Zb&&function(){function a(){var a=ya(g);if(a)try{(a=Va(a))&&(Ba=a.fpid||null)}catch(b){}c()}function b(){c()}function c(){za(d,wa({fpid:Ba,ts:w()}))}var d="tmr_trgfpid",g="rb_sync_id";(function(){var c=ia?ya(d):null;if(c)try{if(c=Va(c))if(Ba=c.fpid||null,864E5>w()-c.ts)return}catch(e){}hb("https://privacy-cs.mail.ru/static/sync-loader.js",a,b)})()}();var Kc="60.5.1",Ta=0,Ea=0,lb=Jb(16),R=null,ca=null,Da=0,ta="tmr_reqNum",Q=null;V&&(Q=P(ta)||null,null!==Q&&fb(ta,gb));
ia&&null===Q&&(Q=ya(ta)||null);Q=null===Q?0:parseInt(Q,10);ia&&za(ta,Q);var la=(V?P("tmr_lvid"):null)||(ia?ya("tmr_lvid"):null),ua=(V?P("tmr_lvidTS"):null)||(ia?ya("tmr_lvidTS"):null);if(null===la||-1===la.search(/^[0-9a-fA-F]+$/))la=Jb(32);Mb("tmr_lvid",la);if(null===ua||-1===ua.search(/^\d+$/))ua=""+w();Mb("tmr_lvidTS",ua);var ba=0,G=[],Ga=[],Za=[],Ya=[],Wa=[],Ua={},Ic="ontouchstart"in f||1<(F.maxTouchPoints||F.msMaxTouchPoints)?"1":"0",Jc=f.devicePixelRatio||0,Hc=function(){var a=f.screen;return a?
a.width+"*"+a.height:""}(),mc=f.performance||f.mozPerformance||f.msPerformance||f.webkitPerformance||{},Na=mc.timing||{},mb=mc.navigation||{},Xb="unloadEventStart unloadEventEnd redirectStart redirectEnd fetchStart domainLookupStart domainLookupEnd connectStart connectEnd secureConnectionStart requestStart responseStart responseEnd domLoading domInteractive domContentLoadedEventStart domContentLoadedEventEnd domComplete loadEventStart loadEventEnd".split(" "),Oa=sa("navigationStart"),dd=sa("domContentLoadedEventStart"),
ed=sa("loadEventStart"),ra=Oa,Yb="downlink downlinkMax effectiveType rtt saveData type".split(" "),Z,Bb;Z=function(a,b,c){if(b&&"object"===typeof b){var d="id"in b&&b.id||ba,g=c.title||null,f,e=Bb(b,{params:c.required,fn:c.fn});if(e.missed.length)console.warn("[TopMailRu]"+(d?"["+d+"]":"")+" Error#1.14","Unspecified "+(1<e.missed.length&&e.missed.slice(0,-1).join(", ")+" and "||"")+e.missed.slice(-1)+" in "+a);else{var k=Bb(b,{params:c.optional,fn:c.fn});f=[].concat(e.values).concat(k.values);e=[].concat(e.missed).concat(k.missed);
c.value&&(b="value"in b&&b.value,!0!==c.value&&(b=b||c.value),b?f.push("value: "+b):e.push("value"));c=f.length?"{ "+f.join(", ")+" }":"";f=e.length?"("+(1<e.length?e.slice(0,-1).join(", ")+" and "+e.slice(-1)+" are":e.slice(-1)+" is")+" empty)":"";d?console.info("[TopMailRu]["+d+"]: "+(g||a)+" "+c+" "+f):console.warn("[TopMailRu] Error#1.15","Undefined counter ID of "+a+" "+c)}}else console.warn("[TopMailRu][]["+a+"] Error#1.13")};Bb=function(a,b){var c=[],d=[],g,f,e;if(b.params)for(g in b.params)if(b.params.hasOwnProperty(g)&&
!1!==b.params[g])if(f=g in a&&a[g],!0!==b.params[g]&&(f=f||b.params[g]),f)try{e=b.fn?b.fn:null,c.push(g+': "'+(e?e(g,f):f)+'"')}catch(k){console.warn("[TopMailRu] Error#1.16",k)}else d&&d.push(g);return{values:c,missed:d}};var x={},Ra=null,Qa=null,ub=[];m.prototype.callbackOnReady=function(a){q&&Z("onReady",a,{title:"OnReady callback"});a&&"object"===typeof a&&"function"===typeof a.callback&&(a.callback.call(a.context||null),ka&&ub.push(a))};m.prototype.pageView=function(a){ja(a);a:if(a&&"object"===
typeof a&&a.id){5>Ga.length&&!M(a.id,Ga)&&(Ga.push(a.id),!1!==a.beat&&Za.push(a.id),G.push(a),Ca&&Nb(a));ka&&(Ua[a.id]=aa(!0,{},a),Ua[a.id].bfCache=!0);"detectBlocker"in a&&!a.detectBlocker&&(ob=!0);var b="string"===typeof a.ecommerce,c=b&&-1!==a.ecommerce.search(/\S/);if(5>Ya.length&&!M(a.id,Ya)&&(!0===a.ecommerce||b&&!c||b&&c||!1!==a.ecommerce&&!b&&(M(a.id,ad)||!M(a.id,bd)))){Ya.push(a.id);if(b&&c){if(wb&&(xb(a.ecommerce),B!==a.ecommerce)){B=a.ecommerce;E&&(E=[0,0,B]);break a}B=a.ecommerce;E&&(E=
[0,0,B])}b=[a.id];if(wb)for(var c=0,d=Xa.length;c<d;c++)Ob(b,Xa[c])}a.timespent=S&&(a.timespent||M(a.id,Yc)&&!1!==a.timespent);S&&(a.timespent?y.enable(a.id):y.disable(a.id));zb||(zb=!0===a.geolocation||a.timespent&&!1!==a.geolocation)&&jc(Ab);jb&&!M(a.id,Wa)&&(Wa.push(a.id),Sb([a.id]))}q&&Z("pageView",a,{title:"Page view",optional:{url:C.href}});W(a)&&(D(J(a,"/counter",!1,!0)),Ea=w())};m.prototype.reachGoal=function(a){ja(a);q&&Z("reachGoal",a,{title:"Reach goal",value:!0,required:{goal:!0}});if(W(a)&&
"goal"in a&&a.goal){var b="value"in a&&a.value?parseInt(a.value)||"":"";D(J(a,"/tracker",!1,!0)+(";e="+escape("RG:"+b+"/"+a.goal)))}};var qb="VALUE";m.prototype.itemView=function(a){q&&Z("itemView",a,{title:"Item view",optional:{list:!0,pagetype:!0,productid:!0,totalvalue:!0},fn:function(a,b){return(""+b).replace(/;/g," ")}});if(W(a)){var b=a.list||"",c=a.productid||"",d=a.pagetype||"",f=a.totalvalue||0,h=Sc(a.id,d,f,c);h&&this.reachGoal(h);(new Image).src="https://ad.mail.ru/retarget/?counter="+
(a.id||ba)+"&list="+b+"&productid="+c+"&pagetype="+d+"&totalvalue="+f+"&_="+Math.random();b="IV:"+f+"/"+(""+b).replace(/;/g," ")+";"+(""+c).replace(/;/g," ")+";"+(""+d).replace(/;/g," ");D(J(a,"/tracker",!1,!0)+(";e="+escape(b)))}};var Tc="vk_ecom_";m.prototype.sendEvent=function(a){ja(a);q&&Z("sendEvent",a,{title:"Send event",value:!0,required:{category:!0,action:!0},optional:{label:!0},fn:function(a,b){return(""+b).substring(0,300).replace(/;/g," ")}});if(W(a)&&"category"in a&&a.category&&"action"in
a&&a.action){var b=(""+a.category).substring(0,300),c=(""+a.action).substring(0,300),d="label"in a&&a.label?(""+a.label).substring(0,300):"",b="CE:"+("value"in a&&a.value?parseInt(a.value)||"":"")+"/"+(""+b).replace(/;/g," ")+";"+(""+c).replace(/;/g," ")+";"+(""+d).replace(/;/g," ");D(J(a,"/tracker",!1,!0)+(";e="+escape(b)))}};m.prototype.setUserID=function(a){if(null===a||!1===a||void 0===a)this.deleteUserID();else{var b=typeof a;"number"!==b&&"string"!==b?q&&console.warn("[TopMailRu] Error#1.17",
"Invalid user ID in setUserID"):(R=a,q&&console.info("[TopMailRu]: Global user ID = "+R))}};m.prototype.getUserID=function(){return R||0===R?R:void 0};m.prototype.deleteUserID=function(){R=null;q&&console.info("[TopMailRu]: Reset global user ID to null")};m.prototype.setUserParams=function(a){if(null===a||!1===a||void 0===a)this.deleteUserParams();else if(O(a)){try{ca=aa(!0,{},a)}catch(b){q&&console.warn("[TopMailRu] Error#1.22","Invalid user params in setUserParams");return}q&&console.info("[TopMailRu]: Global user params = "+
wa(ca))}else q&&console.warn("[TopMailRu] Error#1.21","Invalid user params in setUserParams")};m.prototype.getUserParams=function(){var a=ca?ca:void 0;return a?aa(!0,{},a):void 0};m.prototype.deleteUserParams=function(){ca=null;q&&console.info("[TopMailRu]: Reset global user params to null")};m.prototype.getClientID=function(){var a=la;return a||0===a?a:void 0};m.prototype._MT_event=function(a,b,c){ja(a);q&&Z(b,a,{title:c});W(a)&&D(J(a,"/tracker",!1,!0)+(";e="+escape("MT:/"+b)))};m.prototype.miniAppEvent=
function(a){this._MT_event(a,"miniAppEvent","VK Mini App Event")};var Cb=function(a,b){if(S){var c=y.defaultID();W(a,c)&&(!O(a)||!("activity"in a&&a.activity)?q&&console.warn("[TopMailRu] Error#1.27","Invalid startActivity command: ID of activity is required"):y.startActivity(a.id||c,""+a.activity,null===b?!!a.canUseInBackground:b))}};m.prototype.startTimespent=function(a){Cb(a,null)};m.prototype.startForegroundTimespent=function(a){Cb(a,!1)};m.prototype.startAnytimeTimespent=function(a){Cb(a,!0)};
m.prototype.updateTimespent=function(a){if(S){var b=y.defaultID();W(a,b)&&(!O(a)||!("activity"in a&&a.activity)?y.updateActivity():"number"===typeof a.activity||"string"===typeof a.activity?y.updateActivity(a.id||b,""+a.activity):q&&console.warn("[TopMailRu] Error#1.28","Invalid updateActivity command: ID of activity should be number or string"))}};m.prototype.stopTimespent=function(a){if(S){var b=y.defaultID();W(a,b)&&(!O(a)||!("activity"in a&&a.activity)?y.stopActivity(!1):"number"===typeof a.activity||
"string"===typeof a.activity?y.stopActivity(a.id||b,""+a.activity,!1):q&&console.warn("[TopMailRu] Error#1.29","Invalid stopActivity command: ID of activity should be number or string"))}};m.prototype.incrementEventTimespent=function(a){if(S){var b=y.defaultID();W(a,b)&&(!a||!("activity"in a&&a.activity)?q&&console.warn("[TopMailRu] Error#1.31","Invalid incrementEventTimespent command: ID of countable activity is required"):y.incCount(a.id||b,""+a.activity))}};m.prototype.processEvent=function(a,
b){if(a&&"object"===typeof a)if("type"in a){if("onready"===a.type){if(b&&0>b)return;this.callbackOnReady(a)}else if(b&&0<b)return;switch(a.type){case "pageView":this.pageView(a);break;case "reachGoal":this.reachGoal(a);break;case "itemView":this.itemView(a);break;case "sendEvent":this.sendEvent(a);break;case "setUserID":"userid"in a&&this.setUserID(a.userid);break;case "deleteUserID":this.deleteUserID();break;case "setUserParams":"params"in a&&this.setUserParams(a.params);break;case "deleteUserParams":this.deleteUserParams();
break;case "miniAppEvent":this.miniAppEvent(a);break;case "startTimespent":this.startTimespent(a);break;case "startForegroundTimespent":this.startForegroundTimespent(a);break;case "startAnytimeTimespent":this.startAnytimeTimespent(a);break;case "updateTimespent":this.updateTimespent(a);break;case "stopTimespent":this.stopTimespent(a);break;case "incrementEventTimespent":this.incrementEventTimespent(a)}}else q&&console.warn("[TopMailRu] Error#1.19","Unspecified type of push event");else q&&console.warn("[TopMailRu] Error#1.18",
"Invalid push event")};m.prototype.push=function(a){for(var b=0,c=arguments.length;b<c;b++)this.processEvent(arguments[b])};var nc=!1;m.prototype.onready=function(){nc||(nc=!0,!ob&&!Ca&&$c(Lc,Mc),xb(B),Nc())};var tb=!1;m.prototype.onload=function(){if(!tb){tb=!0;Da=w();if(!Ha&&0<G.length){for(var a=";e="+escape("RT/load")+";et="+Da,b=0;b<G.length;b++)D(J(G[b],"/tracker",!0,!0)+a);Ea=Da}Pc()}};m.prototype.beat=function(){var a;if(!pb&&Ta){var b=w();if(!(12E4<b-Ta)){if(12E4<b-Ea){a=";e="+escape("RT/resend")+
";et="+Da;for(var c=0;c<G.length;c++)!1!==G[c].beat&&D(J(G[c],"/tracker",!1,!0)+a)}else 0<Za.length&&(a=";e="+escape("RT/beat")+";ids="+escape(Za.join()),D(J({id:Za[0]},"/tracker",!1,!0)+a));Ea=b}}};var sb=!1;m.prototype.unload=function(){if(!sb){sb=!0;if(!Ha){var a;a=(a=Tb())?w()-a:void 0;a=";e="+escape("RT/unload")+";et="+w()+(a?";pvt="+escape(a):"");if(ma.support){var b=ma.getLog();a+=";vtauto="+b.auto}for(b=0;b<G.length;b++)D(J(G[b],"/tracker",!0,!0)+a)}ka&&(x.dcl3&&(clearTimeout(x.dcl3),delete x.dcl3),
x.pvt2&&(clearTimeout(x.pvt2),delete x.pvt2),x.pvt15&&(clearTimeout(x.pvt15),delete x.pvt15),x.beat&&(clearInterval(x.beat),delete x.beat))}};m.prototype.activity=function(a){Ta=w()};var ga=_tmr;_tmr=new m;S&&y.init();for(var v=0,Ka=ga.length,qa;v<Ka;v++)(qa=ga[v])&&"object"===typeof qa&&ja(qa);$a=(new Date).getTime();v=0;for(Ka=ga.length;v<Ka;v++)qa=ga[v],_tmr.processEvent(qa,1);La=(new Date).getTime();v=0;for(Ka=ga.length;v<Ka;v++)qa=ga[v],_tmr.processEvent(qa,-1);"complete"===l.readyState||"loading"!==
l.readyState&&!l.documentElement.doScroll?(Qa=dd,_tmr.onready(),dc()):l.addEventListener?n(l,"DOMContentLoaded",Sa):l.attachEvent&&n(l,"readystatechange",Sa);"complete"===l.readyState?(Ra=ed,_tmr.onload()):ka?n(f,"pageshow",rb):n(f,"load",rb);ka?n(f,"pagehide",Fa):(n(f,"unload",Fa),n(f,"beforeunload",Fa));cc();if(!pb)try{for(var oc="scroll gesturechange touchmove mousedown mousemove mouseup touch".split(" "),fd=function(a){n(l,a,function(){_tmr.activity(a)})},v=0;v<oc.length;v++)fd(oc[v]);n(f,"scroll",
function(){_tmr.activity("scallback")})}catch(gd){q&&console.warn("[TopMailRu] Error#1.20",gd)}Ma=(new Date).getTime()}})();
